import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "var(--color-bg)",
        fg: "var(--color-fg)",
        muted: "var(--color-muted)",
        border: "var(--color-border)",
        "btn-bg": "var(--color-btn-bg)",
        "btn-fg": "var(--color-btn-fg)",
        "btn-border": "var(--color-btn-border)",
        accent: "var(--color-accent)",
        "accent-strong": "var(--color-accent-strong)",
        "accent-soft": "var(--color-accent-soft)",
        surface: "var(--color-surface)",
        ink: "var(--color-ink)",
        honey: "var(--color-honey)",
        "honey-strong": "var(--color-honey-strong)",
        "honey-soft": "var(--color-honey-soft)",
        "honey-ink": "var(--color-honey-ink)",
        ok: "var(--color-ok)",
        deny: "var(--color-deny)",
        "ok-soft": "var(--color-ok-soft)",
        "ok-ink": "var(--color-ok-ink)",
        "deny-soft": "var(--color-deny-soft)",
        "deny-ink": "var(--color-deny-ink)",
        warning: "var(--color-warning)",
        "warning-soft": "var(--color-warning-soft)",
        "warning-ink": "var(--color-warning-ink)",
        info: "var(--color-info)",
        "info-soft": "var(--color-info-soft)",
        "info-ink": "var(--color-info-ink)",
        "term-bg": "var(--color-term-bg)",
        "term-fg": "var(--color-term-fg)",
        "term-muted": "var(--color-term-muted)",
        "term-line": "var(--color-term-line)",
        "term-accent": "var(--color-term-accent)",
        "term-ok": "var(--color-term-ok)",
        "term-warn": "var(--color-term-warn)",
        "term-red": "var(--color-term-red)",
        "term-yellow": "var(--color-term-yellow)",
        "term-green": "var(--color-term-green)",
      },
      fontFamily: {
        headline: ["var(--font-neue-machina)", "Arial Black", "sans-serif"],
        body: ["var(--font-inter)", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
